FROM python:3.10-slim

LABEL mantainer="Palenca Team <dev@palenca.com>"

RUN apt-get update
RUN apt-get install -y build-essential

RUN mkdir -p /opt/api

WORKDIR /opt/api

ADD mock/requirements mock/requirements

RUN pip install -r mock/requirements/development.txt

ENV SENTRY_URI http://sentry.io
ENV DOCUMENTATION_URI https://developers.palenca.com
ENV PORT 9000

EXPOSE 9000