FROM python:3.1.0-slim

LABEL mantainer="Palenca Team <dev@palenca.com>"

RUN apt-get update
RUN apt-get install -y build-essential

RUN mkdir -p /opt/api

WORKDIR /opt/api

ADD api/requirements api/requirements

RUN pip install -r api/requirements/testing.txt

COPY . /opt/api

ENV ENVIRONMENT testing
ENV FLASK_ENV testing
ENV DATABASE_TEST_URL sqlite://:memory:
ENV DOCUMENTATION_URI https://developers.palenca.com
ENV SIZE_POOL_AIOHTTP 100

CMD pytest