FROM node:16-alpine

LABEL mantainer="Palenca Team <dev@palenca.com>"

RUN mkdir -p /opt/socket

WORKDIR /opt/socket

ADD socket/package.json /package.json

ADD socket/src /src


RUN npm i
ENV PORT 3000

EXPOSE 3000
