FROM python:3.10-slim

LABEL mantainer="Palenca Team <dev@palenca.com>"

RUN apt-get update
RUN apt-get install -y build-essential

RUN mkdir -p /opt/api

WORKDIR /opt/api

ADD requirements requirements

RUN pip install -r requirements/development.txt

ENV ENVIRONMENT development
ENV SENTRY_URI http://sentry.io
ENV POSTGRES_URI postgres://postgres:@host.docker.internal:5432/palenca_neue
ENV DOCUMENTATION_URI https://developers.palenca.com
ENV PORT 9000

EXPOSE 9000